#' Hierarchical clustering of spectral similarity data
#'
#' \code{CluMSID_HCtbl()} performs hierarchical clustering
#' of spectral similarity data using average linkage
#' as agglomeration criterion.
#'
#' @param distmat A distance matrix as generated by
#' \code{\link{distanceMatrix}}.
#'
#' @param h Height where the tree is to be cut, defaults to \code{0.95}.
#' See \code{\link[stats]{cutree}} for details.
#'
#' @return A \code{data.frame} with name and cluster ID for each
#' feature in \code{distmat}.
#'
#' @seealso \code{\link{CluMSID_HCplot}}
#'
#' @export
CluMSID_HCtbl <- function(distmat, h = 0.95){
  clust <- stats::hclust(stats::as.dist(distmat), method = "average")
  hclusttree <- stats::cutree(clust, h = h)
  hclustmat <- data.frame(feature = names(hclusttree),
                          cluster_ID = unname(hclusttree))

  return(hclustmat)
}

#' Generate cluster dendrogram or heatmap from spectral similarity data
#'
#' \code{CluMSID_HCtbl()} performs hierarchical clustering
#' of spectral similarity data using average linkage
#' as agglomeration criterion like \code{\link{CluMSID_HCtbl}}
#' and generates either a circular dendrogram or a
#' combination of dendrogram and heatmap.
#'
#' @inheritParams CluMSID_HCtbl
#'
#' @param type Specifies which visualisation is to be generated:
#' \code{"dendrogram"} (default) for a circular dendrogram or
#' \code{"heatmap"} for a combination of dendrogram and heatmap.
#'
#' @return A plot as specified by \code{type}.
#'
#' @export
CluMSID_HCplot <- function(distmat, h = 0.95, type = "dendrogram"){
  clust <- stats::hclust(stats::as.dist(distmat), method = "average")
  hclusttree <- stats::cutree(clust, h = h)
  hclustmat <- cbind(names(hclusttree), hclusttree)
  clustorder <- hclusttree[clust$order] # YES, this is right!!!

  nc <- round(max(hclusttree)/8)

  if(type == "heatmap") {
    stats::heatmap(as.matrix(distmat),
            Rowv = stats::as.dendrogram(clust), Colv = "Rowv",
            distfun = NULL, symm = T, margins = c(16,8))
  } else if(type == "dendrogram") {
    clr <- RColorBrewer::brewer.pal(n = 8, name = "Dark2")
    graphics::plot(
      ape::as.phylo(clust),
      type = "fan",
      cex = 0.7,
      tip.color = rep(clr, nc)[clustorder][hclusttree],
      no.margin = TRUE
    )
  } else stop("'type' muste be either 'dendrogram' (default) or 'heatmap'.")
}
