#' Density-based clustering of spectral similarity data
#'
#' \code{CluMSID_OPTICStbl()} performs density-based clustering
#' of spectral similarity data using the OPTICS algorithm.
#'
#' @param distmat A distance matrix as generated by
#' \code{\link{distanceMatrix}}.
#'
#' @param eps,minPts OPTICS parameters, see \code{\link[dbscan]{optics}}.
#'
#' @param eps_cl The reachability distance used for cluster determination,
#' see \code{\link[dbscan:optics]{extractDBSCAN}}.
#'
#' @return A \code{data.frame} with feature name, cluster ID and
#' OPTICS order for each feature in \code{distmat}.
#'
#' @details The function internally uses \code{\link[dbscan]{optics}}
#' and \code{\link[dbscan:optics]{extractDBSCAN}} from the \pkg{dbscan} package.
#'
#' @seealso CluMSID_OPTICSplot
#'
#' @export
CluMSID_OPTICStbl <- function(distmat, eps = 10000, minPts = 3, eps_cl = 0.5){
  opt <- dbscan::optics(stats::as.dist(distmat),
                        eps = eps,
                        minPts = minPts,
                        search = "dist")

  res <- dbscan::extractDBSCAN(opt, eps_cl = eps_cl)

  clustmat <- data.frame(
    feature = colnames(as.matrix(distmat)),
    cluster_ID = res$cluster,
    OPTICS_order = match(seq_along(colnames(as.matrix(distmat))), res$order)
  )

  return(clustmat)
}

#' Visualisation of density-based clustering of spectral similarity data
#'
#' \code{CluMSID_OPTICSplot()} performs density-based clustering
#' of spectral similarity data using the OPTICS algorithm like
#' \code{\link{CluMSID_OPTICStbl}} and creates a reachability distance plot.
#'
#' @inheritParams CluMSID_OPTICStbl
#'
#' @return A reachability distance plot as visualisation of OPTICS clustering,
#' see code{\link[dbscan:optics]{extractDBSCAN}}.
#'
#' @details The function internally uses \code{\link[dbscan]{optics}}
#' and \code{\link[dbscan:optics]{extractDBSCAN}} from the \pkg{dbscan} package.
#'
#' @seealso CluMSID_OPTICStbl
#'
#' @export
CluMSID_OPTICSplot <- function(distmat, eps = 10000, minPts = 3, eps_cl = 0.5){
  opt <- dbscan::optics(stats::as.dist(distmat),
                        eps = eps,
                        minPts = minPts,
                        search = "dist")

  res <- dbscan::extractDBSCAN(opt, eps_cl = eps_cl)

  opal <- grDevices::palette()
  grDevices::palette(c(opal, rep(c("orange", opal[-1]),10)))
  graphics::plot(res)
  grDevices::palette(opal)
}
